# Generated by Django 4.0.1 on 2022-01-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Persons',
        ),
    ]
