# Generated by Django 4.0.1 on 2022-01-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_users_persons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Имя'),
        ),
    ]
